[project]
name = "etl-vector-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "chromadb>=1.5.9",
    "click>=8.4.2",
    "loguru>=0.7.3",
    "lxml>=6.1.1",
    "matplotlib>=3.11.1",
    "mysqlclient>=2.2.8",
    "pandas>=3.0.5",
    "pymysql>=1.2.0",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "schedule>=1.2.2",
]
